# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: guillaumev/filhosdeangola

media_folder: /assets
public_folder: /

collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: /_posts
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, type: date }
